# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

graffle_device_internal <- function(bg, width, height, pointsize, res, clip, antialias, drawing, aliases) {
    .Call('_graffle_graffle_device_internal', PACKAGE = 'graffle', bg, width, height, pointsize, res, clip, antialias, drawing, aliases)
}

